# Monokai Pro Spectrum - WezTerm Configuration

[colors]
foreground = "#f7f1ff"
background = "#222222"
cursor_bg = "#f7f1ff"
cursor_border = "#f7f1ff"
cursor_fg = "#222222"
selection_bg = "#363537"
selection_fg = "#f7f1ff"

[colors.ansi]
black = "#222222"
red = "#fc618d"
green = "#7bd88f"
yellow = "#fce566"
blue = "#5ad4e6"
magenta = "#948ae3"
cyan = "#5ad4e6"
white = "#f7f1ff"

[colors.brights]
black = "#363537"
red = "#fc618d"
green = "#7bd88f"
yellow = "#fce566"
blue = "#5ad4e6"
magenta = "#948ae3"
cyan = "#5ad4e6"
white = "#f7f1ff"
